apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: appui
labels:
  app: appui
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: appui
      tier: appui
  spec:
    containers:
      - name: appui
        image: manojkumark/devops_ui:VERSION
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: appui
