apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appui
  namespace: default
spec:
  selector:
    matchLabels:
      run: appui
  template:
    metadata:
      labels:
        run: appui
    spec:
      containers:
        - image: manojkumark/devops_ui:VERSION
          imagePullPolicy: IfNotPresent
          name: appui
          ports:
            - containerPort: 80
              protocol: TCP
