apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appui-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "kube"
spec:
  backend:
    serviceName: appui-service
    servicePort: 7000
